services:
    davidiq.reimg.listener:
        class: davidiq\reimg\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
